In [1]:
import pandas as pd  

df=pd.read_csv("transactions.csv")
df

,t_date,cust_id,t_amt,services,products_used,city,state,t_details
0,06-26-2015,4007024,40.33,Exercise & Fitness,Cardio Machine Accessories,Clarksville,Tennessee,credit
1,05-26-2015,4006742,198.44,Exercise & Fitness,Weightlifting Gloves,Long Beach,California,credit
2,06-01-2015,4009775,5.58,Exercise & Fitness,Weightlifting Machine Accessories,Anaheim,California,credit
3,06-05-2015,4002199,198.19,Gymnastics,Gymnastics Rings,Milwaukee,Wisconsin,credit
4,12-17-2015,4002613,98.81,Team Sports,Field Hockey,Nashville,Tennessee,credit
...,...,...,...,...,...,...,...,...
49995,09-18-2015,4005664,53.95,Games,Dice Games,Irving,Texas,credit
49996,10-02-2015,4007287,163.81,Games,Poker Chips & Sets,Kansas City,Missouri,credit
49997,05-03-2015,4003954,35.85,Racquet Sports,Squash,New Orleans,Louisiana,cash
49998,10-23-2015,4007843,180.41,Gymnastics,Vaulting Horses,Berkeley,California,credit
49999,12-14-2015,4001406,168.49,Team Sports,Team Handball,Rockford,Illinois,credit

In [2]:
#1 What is the total sales amount across all transactions?

amount=df["t_amt"].sum() #using sum method to return total sales amount 
amount

np.float64(5110820.54)

In [3]:
#2 Which month had the highest total transaction amount?


d = pd.to_datetime(df['t_date'],errors='coerce',dayfirst=True) #to convert it into datetime format (day first - it will return the days first)
t=d.dt.month_name() # coverting this t_date to month using month_name() method
df['month']=t #giving the name as month 
m=df.groupby('month')['t_amt'].sum().idxmax() #grouping them and returning the month that is having the highest total t_amt
m
df
#idxmax - returns the index of the maximum value

/var/folders/lt/qw_mkrm13513bwbcc1kjrx9r0000gp/T/ipykernel_18796/3555084825.py:4: UserWarning: Parsing dates in %m-%d-%Y format when dayfirst=True was specified. Pass `dayfirst=False` or specify a format to silence this warning.
  d = pd.to_datetime(df['t_date'],errors='coerce',dayfirst=True) #to convert it into datetime format (day first - it will return the days first)

,t_date,cust_id,t_amt,services,products_used,city,state,t_details,month
0,06-26-2015,4007024,40.33,Exercise & Fitness,Cardio Machine Accessories,Clarksville,Tennessee,credit,June
1,05-26-2015,4006742,198.44,Exercise & Fitness,Weightlifting Gloves,Long Beach,California,credit,May
2,06-01-2015,4009775,5.58,Exercise & Fitness,Weightlifting Machine Accessories,Anaheim,California,credit,June
3,06-05-2015,4002199,198.19,Gymnastics,Gymnastics Rings,Milwaukee,Wisconsin,credit,June
4,12-17-2015,4002613,98.81,Team Sports,Field Hockey,Nashville,Tennessee,credit,December
...,...,...,...,...,...,...,...,...,...
49995,09-18-2015,4005664,53.95,Games,Dice Games,Irving,Texas,credit,September
49996,10-02-2015,4007287,163.81,Games,Poker Chips & Sets,Kansas City,Missouri,credit,October
49997,05-03-2015,4003954,35.85,Racquet Sports,Squash,New Orleans,Louisiana,cash,May
49998,10-23-2015,4007843,180.41,Gymnastics,Vaulting Horses,Berkeley,California,credit,October
49999,12-14-2015,4001406,168.49,Team Sports,Team Handball,Rockford,Illinois,credit,December

In [4]:
#3 What is the average transaction amount per customer?
df.groupby('cust_id')['t_amt'].mean()

cust_id
4000000    127.444000
4000001    108.945556
4000002     56.165000
4000003    123.670000
4000004    168.135000
              ...
4009995     65.018571
4009996    104.515000
4009997    121.547500
4009998    110.950000
4009999     85.252500
Name: t_amt, Length: 9926, dtype: float64

In [5]:
#4 What is the trend of total sales over months?
date=pd.to_datetime(df['t_date'],errors='coerce') #converting into date time format
df['t_amt']=pd.to_numeric(df['t_amt'],errors='coerce') #converting total amount to numeric

month=d.dt.to_period("M") #dt - it is used to extract or manipulate datetime properties from pandas
df['year_month']=month #converting monelty period for grouping 


sales=df.groupby('year_month')['t_amt'].sum().reset_index() #finding out the sales by grouping year and amount 
sales.sort_values('year_month')

   year_month      t_amt
0     2015-01  438165.76
1     2015-02  395262.37
2     2015-03  444664.24
3     2015-04  420695.24
4     2015-05  432627.58
5     2015-06  421074.55
6     2015-07  439560.80
7     2015-08  434255.01
8     2015-09  429321.63
9     2015-10  424856.28
10    2015-11  408846.35
11    2015-12  421490.73

In [6]:
#5 What is the highest single transaction amount recorded?

df['t_amt']=pd.to_numeric(df['t_amt'],errors='coerce')
high=df['t_amt'].max()
high

200.0

In [7]:
#6 Which service category contributes the most to total revenue?

rev=df.groupby('services')['t_amt'].sum()
rev.loc[[rev.idxmax()]] #loc will return the label based indexing

services
Outdoor Recreation    846678.64
Name: t_amt, dtype: float64

In [8]:
#7 Which product generated the highest revenue?

pro=df.groupby('products_used')['t_amt'].sum()
pro.loc[[pro.idxmax()]]

products_used
Yoga & Pilates    47804.94
Name: t_amt, dtype: float64

In [9]:
#8 How does the average transaction amount vary between services?

df['t_amt']=pd.to_numeric(df['t_amt'],errors='coerce')
ser=df.groupby('services')['t_amt'].mean()
ser

services
Air Sports                103.455104
Combat Sports             101.061761
Dancing                   102.907512
Exercise & Fitness        103.660247
Games                     102.272968
Gymnastics                102.385901
Indoor Games              103.074684
Jumping                   102.155171
Outdoor Play Equipment    101.281196
Outdoor Recreation        100.999480
Puzzles                   100.595997
Racquet Sports            103.647461
Team Sports               102.738998
Water Sports              101.899975
Winter Sports             101.217718
Name: t_amt, dtype: float64

In [10]:
#9 How many unique customers made purchases?

df['cust_id'].nunique()

9926

In [11]:
#10 Which customers have spent the most overall?
cus=df.groupby('cust_id')['t_amt'].sum()
cus.loc[[cus.idxmax()]]

cust_id
4009485    1973.3
Name: t_amt, dtype: float64

In [12]:
#11 What is the average number of transactions per customer?

df.groupby('cust_id').size().mean() #size - counts the number of rows

np.float64(5.037275841225066)

In [13]:
#12 Are there customers who made multiple purchases in different categories?

mul=df.groupby('cust_id')['products_used'].nunique()
mul[mul>1]

cust_id
4000000    5
4000001    9
4000002    2
4000003    3
4000004    4
          ..
4009995    7
4009996    8
4009997    4
4009998    6
4009999    7
Name: products_used, Length: 9577, dtype: int64

In [14]:
#13 What percentage of customers are repeat buyers?

((df.groupby('cust_id').size() > 1).mean()) * 100

np.float64(96.5645778762845)

In [15]:
#14 Which product category has the highest total sales?

sale=df.groupby('products_used')['t_amt'].sum()
sale.loc[[sale.idxmax()]]

products_used
Yoga & Pilates    47804.94
Name: t_amt, dtype: float64

In [16]:
#15 Which services are most popular by transaction count?

s=df.groupby('services').size()
s.loc[[s.idxmax()]]

services
Outdoor Recreation    8383
dtype: int64

In [17]:
#16 For each service, which product type is purchased most frequently?

freq = df.groupby(['services', 'products_used']).size().reset_index(name='count')

freq.loc[freq.groupby('services')['count'].idxmax()]

                   services               products_used  count
2                Air Sports                  Parachutes    400
3             Combat Sports                      Boxing    431
7                   Dancing                 Ballet Bars    414
9        Exercise & Fitness  Cardio Machine Accessories    445
32                    Games                     Mahjong    437
35               Gymnastics               Balance Beams    425
47             Indoor Games                    Foosball    422
54                  Jumping                 Trampolines    421
60   Outdoor Play Equipment                  Swing Sets    464
73       Outdoor Recreation                  Lawn Games    466
83                  Puzzles              Jigsaw Puzzles    397
85           Racquet Sports                   Badminton    413
97              Team Sports                      Hockey    434
105            Water Sports                Bodyboarding    425
118           Winter Sports        Cross-Country Skiing    429

In [18]:
#19 Which state has the highest total sales?

state = df.groupby('state')['t_amt'].sum()
state.loc[[state.idxmax()]]

state
California    702346.23
Name: t_amt, dtype: float64

In [19]:
#20 Which city records the highest number of transactions?

df.groupby('city').size().idxmax()

'Pasadena'

In [20]:
#21 What is the average spending per transaction in each state?

df.groupby('state')['t_amt'].mean()

state
Alabama                 102.487049
Arizona                 102.172241
California              102.652182
Colorado                101.537415
Connecticut              99.982108
District of Columbia    103.800334
Florida                 103.136567
Georgia                 102.330675
Hawaii                  101.536667
Idaho                    98.969538
Illinois                100.166315
Indiana                 100.712664
Iowa                    103.100727
Kansas                  101.436926
Kentucky                104.130392
Louisiana               103.466335
Maryland                100.506913
Massachusetts           104.541571
Michigan                101.547777
Minnesota               103.465157
Mississippi             101.214926
Missouri                100.969040
Nebraska                101.955690
Nevada                  105.434718
New Jersey              103.438005
New York                100.259452
North Carolina          103.033172
Ohio                    101.350817
Oklahoma                104.995771
Oregon                  102.438143
Pennsylvania            102.776034
South Carolina          103.540065
Tennessee                99.265804
Texas                   101.379891
Utah                    104.507560
Virginia                104.976206
Washington              101.401603
Wisconsin               101.953159
Name: t_amt, dtype: float64

In [21]:
#23 Which states buy the most Outdoor Recreation products?

out=df[df['products_used']=="Outdoor Recreation"]
count=out.groupby('state').size()
count.loc[[count.idxmax()]]

ValueError: attempt to get argmax of an empty sequence

In [ ]:
#27 What is the total number of transactions per month?

df['t_date'] = pd.to_datetime(df['t_date'], errors='coerce')
df['year_month'] = df['t_date'].dt.to_period('M')
monthly = df.groupby('year_month').size()
monthly

year_month
2015-01    4268
2015-02    3834
2015-03    4360
2015-04    4175
2015-05    4205
2015-06    4171
2015-07    4252
2015-08    4250
2015-09    4160
2015-10    4181
2015-11    3994
2015-12    4150
Freq: M, dtype: int64